In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/excel files/2_pandas_weather_data.csv")

In [ ]:
df

          day  temperature  windspeed  event
0  01-01-2017           32          6   Rain
1  02-01-2017           35          7  Sunny
2  03-01-2017           28          2   Snow

In [ ]:
dfe=pd.read_excel("/content/drive/MyDrive/excel files/2_pandas_weather_data.xlsx")

In [ ]:
dfe

         day  temperature  windspeed  event
0 2017-01-01           32          6   Rain
1 2017-01-02           35          7  Sunny
2 2017-01-03           28          2   Snow

In [ ]:
weather_data = {'day': ['1/1/2017','1/2/2017','1/3/2017'],'temperature': [32,35,28],'windspeed': [6,7,2],'event': ['Rain', 'Sunny', 'Snow']}

In [ ]:
weather_df=pd.DataFrame(weather_data)

In [ ]:
weather_df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

creating a data frame using list of dictionaries

In [ ]:
weather_data = [{'day': '1/1/2017', 'temperature': 32, 'windspeed': 6, 'event': 'Rain'},{'day': '1/2/2017', 'temperature': 35, 'windspeed': 7, 'event': 'Sunny'},{'day': '1/3/2017', 'temperature': 28, 'windspeed': 2, 'event': 'Snow'},]

In [ ]:
weather_df_dict=pd.DataFrame(data=weather_data,columns=["day","temperature","windspeed","event"])

In [ ]:
weather_df_dict

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow