In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
df = pd.DataFrame({'A':[1,2,np.nan],'B':[5,np.nan,np.nan],'C':[1,2,3]})

In [ ]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [ ]:
df.dropna()

     A    B  C
0  1.0  5.0  1

In [ ]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [ ]:
df.dropna(axis=1)

   C
0  1
1  2
2  3

In [ ]:
df.dropna(thresh=2)

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [ ]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [ ]:
df.fillna(value="fill value")

            A           B  C
0         1.0         5.0  1
1         2.0  fill value  2
2  fill value  fill value  3

In [ ]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [ ]:
df.fillna(value=0,inplace=True)

In [ ]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  0.0  2
2  0.0  0.0  3

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      float64
 1   B       3 non-null      float64
 2   C       3 non-null      int64
dtypes: float64(2), int64(1)
memory usage: 200.0 bytes

In [ ]:
df.shape

(3, 3)